### ISSUE TITLE
Feature: User can view a list of recipes.

### ISSUE THREAD

**Issue by codewithbingle** [codewithbingle/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of recipes.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to have a glimpse of various recipes that they can choose from. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90303824/231916593-2b7060c4-668e-4b25-9865-612df986f854.png)
![image](https://user-images.githubusercontent.com/90303824/231916619-40f1a879-e3f7-408a-b82a-b8af8e0b8ec4.png)
![image](https://user-images.githubusercontent.com/90303824/231916650-99370851-c630-4976-8f37-08012c23b66d.png)
![image](https://user-images.githubusercontent.com/90303824/231916680-3f6402b9-c3e5-4739-8dfd-325cc6178a9b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create the HTML for the homepage.
  - [ ] Create a Navigation Bar, along with the logo and links for Home, Recipes, and Favorites.
  - [ ] Create a filter list of recipes.
  - [ ] Make sure that click targets are either `<a>` or `<button>` elements.
  - [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Write CSS to match the styling of wireframes on Figma
  - [ ] Start with writing CSS for the mobile device.
  - [ ] Adjust the styling as needed to adapt to the desktop screen.  
- [ ] Use API and JSON to generate a filtered list of recipes.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented-out codes.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
