### ISSUE TITLE
Feature: User can filter recipes by category.

### ISSUE THREAD

**Issue by codewithbingle** [codewithbingle/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can filter recipes by category.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can filter it according to the category they choose. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90303824/231923204-21c9e872-0829-41b9-8eab-bd07d3f72bb7.png)
![image](https://user-images.githubusercontent.com/90303824/231923249-ca86da30-59fe-4889-9a48-b02ab300b9d5.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create the HTML page that will show the filtered Category list. 
- [ ]  Write CSS to match the styling of wireframes on Figma
  - [ ] Start with writing CSS for the mobile device.
  - [ ] Adjust the styling as needed to adapt to the desktop screen.

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
