### ISSUE TITLE
Feature: User can like a the recipe. 

### ISSUE THREAD

**Issue by codewithbingle** [codewithbingle/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can like a photo of the recipe.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can like the recipe. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90303824/231924499-40f21b56-460d-4a0a-8b79-133470e8a363.png)
![image](https://user-images.githubusercontent.com/90303824/231924529-57419952-14ae-4db8-ab6f-c377a57dc0d9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- Create the heart-shape like button. 
- [ ]  Write CSS to match the styling of wireframes on Figma
  - [ ] Start with writing CSS for the mobile device.
  - [ ] Adjust the styling as needed to adapt to the desktop screen.

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
