### ISSUE TITLE
Feature: User can save their favorite recipes.

### ISSUE THREAD

**Issue by codewithbingle** [codewithbingle/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save their favorite recipes. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User is able to save their favorite recipes so that they are able to compile the chosen recipes they like. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90303824/231926060-8f90e39e-6e40-4086-a49c-4681ee6a23ad.png)

![image](https://user-images.githubusercontent.com/90303824/231926106-0021c436-1f44-4350-9a14-f49965f83522.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create a save button.
  - [ ] Make sure that click targets are either `<a>` or `<button>` elements.
  - [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Write CSS to match the styling of wireframes on Figma
  - [ ] Start with writing CSS for the mobile device.
  - [ ] Adjust the styling as needed to adapt to the desktop screen.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
