### ISSUE TITLE
Feature: User can view the list of recipes they previously saved.

### ISSUE THREAD

**Issue by codewithbingle** [codewithbingle/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the list of recipes they previously saved.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users are able to view all the recipes that they have saved. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/90303824/231926199-c62ccb0a-078f-494b-a165-f05a611af0f7.png)
![image](https://user-images.githubusercontent.com/90303824/231926227-135cc4bd-10b1-4b66-8fe8-f1dc62a440b7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Create an HTML file.
- [ ]  Write CSS to match the styling of wireframes on Figma
  - [ ] Start with writing CSS for the mobile device.
  - [ ] Adjust the styling as needed to adapt to the desktop screen.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
